### ISSUE TITLE
Marshal Command Code doesn't work after installation

### ISSUE THREAD

**Issue by DerpNerb** [42iscool42/MCC#50]
**Version:** Marshal Command Code v2.0.9
**Description:** When installing this package onto my laptop, the syntax doesn't seem to work properly. It recognizes the .mcfunction files, but it doesn't really color them. It's just white. It does recognize errors though...
I don't have other packages installed. I have tried reinstalling the package but it keeps doing this. 
Am I missing something?

**Screenshot:**
![image](https://user-images.githubusercontent.com/39121384/45684485-ce6aa300-bb46-11e8-8738-1c53d5334e67.png)

**Comment by DerpNerb** [comment]
None, that's the problem I think.

I checked my PC, and it has a package called MCC installed (that's the color scheme I assume) 
But I don't remember installing it.. Also I cant find MCC in the package browser, so I don't know how to get it on my laptop.

**Comment by 42iscool42** [comment]
MCC is just an abbreviation for Marshal Command Code, so that package is this.
Can you check a couple of things for me:
1. In the menu bar, open preferences then select color scheme.  Tell me which one is highlighted
2. Press control and hit the ` key at the same time. This should open a new pane in the window.  Copy all the text from this area and paste it here as well.

**Comment by DerpNerb** [comment]
Interesting, when clicking the color scheme option, the syntax suddenly started working :D
Now it works for every color scheme!

Even when reinstalling the package, now it instantly works, so I think i just needed to click the color scheme option for it to snap in or something :)

Anyway, thanks for your help! My friend also has this problem so I now know how to fix it!

**Comment by DerpNerb** [comment]
So I got the "bug" again on my pc after deleting the MCC folder, the fix was again to just open preferences -> color scheme, then it instantly works again.

My console output from that is:

DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/derp/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/derp/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/derp/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.115242
startup time: 0.146242
first paint time: 0.147242
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AutoWrap.autowrap
reloading plugin Bootstrap 3 Autocomplete.bootstrap_3_autocomplete
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin JsFormat.js_formatter
reloading plugin Marshal Command Code.__init__
reloading plugin Marshal Command Code.Blocks
reloading plugin Marshal Command Code.ColorSchemeEditor
reloading plugin Marshal Command Code.CommandTree
reloading plugin Marshal Command Code.Data
reloading plugin Marshal Command Code.Items
reloading plugin Marshal Command Code.MccHighlighting
reloading plugin Marshal Command Code.Parser
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\MccHighlighting.py", line 40, in plugin_loaded
    ColorSchemeEditor.edit_color_scheme()
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 30, in edit_color_scheme
    ColorSchemeEditor.edit_plist_color_scheme(original_color_scheme)
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 79, in edit_plist_color_scheme
    scheme_data = plistlib.readPlistFromBytes(sublime.load_binary_resource(original_color_scheme))
  File "C:\Program Files\Sublime Text 3\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
Package Control: Unable to remove old directory JavaScript Completions - deferring until next start
Package Control: Installing 1 upgrades
ignored packages updated to: ["Marshal Command Code", "Vintage"]
unloading plugin Marshal Command Code.__init__
unloading plugin Marshal Command Code.Blocks
unloading plugin Marshal Command Code.ColorSchemeEditor
unloading plugin Marshal Command Code.CommandTree
unloading plugin Marshal Command Code.Data
unloading plugin Marshal Command Code.Items
unloading plugin Marshal Command Code.MccHighlighting
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 30, in edit_color_scheme
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 79, in edit_plist_color_scheme
  File "C:\Program Files\Sublime Text 3\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
unloading plugin Marshal Command Code.Parser
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 30, in edit_color_scheme
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 79, in edit_plist_color_scheme
  File "C:\Program Files\Sublime Text 3\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Upgraded Marshal Command Code to 2.0.10
ignored packages updated to: ["Vintage"]
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 30, in edit_color_scheme
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 79, in edit_plist_color_scheme
  File "C:\Program Files\Sublime Text 3\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin Marshal Command Code.__init__
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package
reloading plugin Marshal Command Code.Blocks
reloading plugin Marshal Command Code.ColorSchemeEditor
reloading plugin Marshal Command Code.CommandTree
reloading plugin Marshal Command Code.Data
reloading plugin Marshal Command Code.Items
reloading plugin Marshal Command Code.MccHighlighting
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 183, in reload_plugin
    m.plugin_loaded()
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\MccHighlighting.py", line 40, in plugin_loaded
    ColorSchemeEditor.edit_color_scheme()
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 30, in edit_color_scheme
    ColorSchemeEditor.edit_plist_color_scheme(original_color_scheme)
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 79, in edit_plist_color_scheme
    scheme_data = plistlib.readPlistFromBytes(sublime.load_binary_resource(original_color_scheme))
  File "C:\Program Files\Sublime Text 3\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 30, in edit_color_scheme
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 79, in edit_plist_color_scheme
  File "C:\Program Files\Sublime Text 3\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
reloading plugin Marshal Command Code.Parser
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 30, in edit_color_scheme
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 79, in edit_plist_color_scheme
  File "C:\Program Files\Sublime Text 3\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 30, in edit_color_scheme
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 79, in edit_plist_color_scheme
  File "C:\Program Files\Sublime Text 3\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\derp\AppData\Roaming\Sublime Text 3\Installed Packages\Marshal Command Code.sublime-package\ColorSchemeEditor.py", line 24, in edit_color_scheme
AttributeError: 'NoneType' object has no attribute 'load_settings'

**Comment by 42iscool42** [comment]
The reason for this is that MCC makes it's own version of the color scheme and then saves it in that folder you deleted. When the folder was deleted, MCC didn't realize the converted scheme was gone and so didn't convert it again. Did you delete the MCC folder before the first time as well?

**Comment by DerpNerb** [comment]
No the way I knew about this bug is because I recommended this awesome package to a friend, and after installation it didn't work for him.
I never had this problem when installing the package, so that's why I installed it on my laptop, and bam: same problem occurs.
